---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: secondTargetGroupAttacker

description: 

conditions:
  allOf:
    - property:
        name: againAnotherPropertyOfAnotherType
        operator: is-undefined
